-- Delete All Data Script - Run this before 01-setup-lead-management.sql
-- This script safely deletes all data while respecting foreign key relationships
-- Disables RLS temporarily to allow deletion

-- Disable RLS temporarily for cleanup
ALTER TABLE IF EXISTS role_access_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS city_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS niche_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lead_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS niches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;

-- Delete all data in order of foreign key dependencies
DELETE FROM role_access_log;
DELETE FROM city_assignments;
DELETE FROM niche_assignments;
DELETE FROM user_assignments;
DELETE FROM activity_log;
DELETE FROM lead_responses;
DELETE FROM leads;
DELETE FROM cities;
DELETE FROM niches;
DELETE FROM users;

-- Re-enable RLS
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS niches ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lead_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS niche_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS city_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS role_access_log ENABLE ROW LEVEL SECURITY;

-- Drop all tables in correct order (reverse of creation, respecting foreign keys)
DROP TABLE IF EXISTS role_access_log CASCADE;
DROP TABLE IF EXISTS city_assignments CASCADE;
DROP TABLE IF EXISTS niche_assignments CASCADE;
DROP TABLE IF EXISTS user_assignments CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS lead_responses CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS niches CASCADE;
DROP TABLE IF EXISTS users CASCADE;